version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres-demo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring-app-demo
#    restart: always
#    ports:
#      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - postgres
#      - redis
#    networks:
#      - app-network

volumes:
  pgdata:

